# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000105)
$foreground = rgb(FDEFE2)
$color0 = rgb(000105)
$color1 = rgb(2D344C)
$color2 = rgb(503A56)
$color3 = rgb(5C3F51)
$color4 = rgb(934C57)
$color5 = rgb(A35058)
$color6 = rgb(BB9C82)
$color7 = rgb(F4DFCE)
$color8 = rgb(AB9C90)
$color9 = rgb(3C4565)
$color10 = rgb(6A4D73)
$color11 = rgb(7B546C)
$color12 = rgb(C46574)
$color13 = rgb(D96A76)
$color14 = rgb(F9D0AD)
$color15 = rgb(F4DFCE)
