# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(00000A)
$foreground = rgb(E6F0F4)
$color0 = rgb(0F0E15)
$color1 = rgb(3A3A55)
$color2 = rgb(354946)
$color3 = rgb(51597D)
$color4 = rgb(5E7C9D)
$color5 = rgb(899FA8)
$color6 = rgb(899FA8)
$color7 = rgb(D2E1E7)
$color8 = rgb(939EA2)
$color9 = rgb(4D4D71)
$color10 = rgb(46615E)
$color11 = rgb(6C77A7)
$color12 = rgb(7DA5D1)
$color13 = rgb(B7D4E0)
$color14 = rgb(B7D4E0)
$color15 = rgb(D2E1E7)
