# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2C292A)
$foreground = rgb(FCECDE)
$color0 = rgb(524E50)
$color1 = rgb(291C22)
$color2 = rgb(6E4D4C)
$color3 = rgb(6E4D4C)
$color4 = rgb(6E4D4C)
$color5 = rgb(B89779)
$color6 = rgb(B89779)
$color7 = rgb(F2DCC8)
$color8 = rgb(A99A8C)
$color9 = rgb(36252D)
$color10 = rgb(936666)
$color11 = rgb(936666)
$color12 = rgb(936666)
$color13 = rgb(F5C9A1)
$color14 = rgb(F5C9A1)
$color15 = rgb(F2DCC8)
