# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(252428)
$foreground = rgb(EEE7EF)
$color0 = rgb(4B494E)
$color1 = rgb(2D293B)
$color2 = rgb(342F41)
$color3 = rgb(4B4463)
$color4 = rgb(635A6C)
$color5 = rgb(938697)
$color6 = rgb(9A8C9E)
$color7 = rgb(DED5E0)
$color8 = rgb(9B959D)
$color9 = rgb(3C364E)
$color10 = rgb(453E56)
$color11 = rgb(645B84)
$color12 = rgb(847890)
$color13 = rgb(C4B3CA)
$color14 = rgb(CDBBD2)
$color15 = rgb(DED5E0)
