#!/usr/bin/env bash
# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  ##
# Wallust Colors for current wallpaper

cache_dir="$HOME/.cache/awww"

wallpaper_from_cache() {
    local cache_file="$1"
    local entry
    local cache_entries=()

    # Current awww cache files are NUL-delimited. Keep the line fallback for
    # older cache files generated by earlier awww releases.
    mapfile -d '' -t cache_entries < "$cache_file"
    for entry in "${cache_entries[@]}"; do
        if [[ -f "$entry" ]]; then
            printf '%s\n' "$entry"
            return 0
        fi
    done

    while IFS= read -r entry; do
        if [[ -f "$entry" ]]; then
            printf '%s\n' "$entry"
            return 0
        fi
    done < "$cache_file"

    return 1
}

wallpaper_path="$1"

if [[ -z "$wallpaper_path" ]]; then
    current_monitor=$(hyprctl monitors | awk '/^Monitor/{name=$2} /focused: yes/{print name}')
    cache_file="$cache_dir/$current_monitor"

    if [[ -f "$cache_file" ]]; then
        wallpaper_path=$(wallpaper_from_cache "$cache_file")
    fi
fi

if [[ ! -f "$wallpaper_path" ]]; then
    echo "Unable to find the current wallpaper for Wallust."
    exit 1
fi

echo "Found wallpaper: $wallpaper_path"

mkdir -p "$HOME/.config/rofi"
mkdir -p "$HOME/.config/hypr/wallpaper_effects"
mkdir -p "$HOME/.config/hypr/wallust"

ln -sf -- "$wallpaper_path" "$HOME/.config/rofi/.current_wallpaper"
cp -f -- "$wallpaper_path" "$HOME/.config/hypr/wallpaper_effects/.wallpaper_current"

# Keep the previous desktop palette for Hyprlock before Wallust overwrites it.
hypr_colors="$HOME/.config/hypr/wallust/wallust-hyprland.conf"
hyprlock_colors="$HOME/.config/hypr/wallust/hyprlock-colors.conf"
if [[ -s "$hypr_colors" ]]; then
    cp -f -- "$hypr_colors" "$hyprlock_colors"
fi

# Keep Wallust in the foreground so refresh scripts see generated templates.
wallust run "$wallpaper_path" -s
