#Commands & Apps to be executed at launch

$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts

$wallDIR=$HOME/Pictures/wallpapers
$lock = $scriptsDir/LockScreen.sh
$SwwwRandom = $UserScripts/WallpaperAutoChange.sh

# wallpaper stuff / More wallpaper options below
exec-once = uwsm app -- awww-daemon --format xrgb


# Startup
# exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec = hyprctl setcursor Bibata-Modern-Classic  22
# exec-once = uwsm app -- bash $HOME/dotfiles/scripts/startups/connect_realmebuds.sh
exec-once = uwsm app -- bash $HOME/.config/hypr/scripts/temp_show.sh
exec-once = xhost +SI:localuser:root
exec-once = uwsm app -- kanshi

# starup apps
exec-once = uwsm app -- waybar
# exec-once = autokey-qt   &
# exec-once = slimbookbatterypreferences.py &
exec-once = uwsm app -- nm-applet --indicator
exec-once = uwsm app -- ags
exec-once = uwsm app -- blueman-applet
exec-once = uwsm app -- ydotoold

# Starting hypridle to start hyprlock
exec-once = uwsm app -- hypridle

# Start pyprland daemon
exec-once = uwsm app -- pypr
