map dm console mount
map cd console z%space
map cD console zi%space
map iv shell -f ~/.config/ranger/scripts/sxiv-current-dir %f
map iV shell ~/.config/ranger/scripts/sxiv-fzf %d
map ex extract
map eX extract_to_dirs
map er extract_raw%space
map ec compress%space
map dD console delete
map du shell ncdu
map yd dragon
map gd cd ~/Downloads
map gs cd ~/Pictures/Screenshots/
map gv cd ~/Videos/


default_linemode devicons
set colorscheme devicons_slate
set draw_borders both

set preview_images true
set preview_images_method kitty
set preview_script ~/.config/ranger/scope.sh
set use_preview_script true
set preview_files true
set preview_directories true
set collapse_preview false
set update_tmux_title false
