return {
  --   {
  --     "williamboman/mason.nvim",
  --     lazy = false,
  --     priority = 1000,
  --     opts = {
  --       ui = {
  --         icons = {
  --           package_installed = "✓",
  --           package_pending = "➜",
  --           package_uninstalled = "✗",
  --         },
  --       },
  --     },
  --   },
  --
  --   {
  --     "williamboman/mason-lspconfig.nvim",
  --     dependencies = { "williamboman/mason.nvim" },
  --     lazy = false,
  --     priority = 1000,
  --     opts = {
  --       ensure_installed = {
  --         "lua_ls",
  --         "bashls",
  --         "jsonls",
  --         "pyright",
  --         "clangd",
  --         "gopls",
  --         "html",
  --         "dockerls",
  --         "yamlls",
  --         "marksman",
  --       },
  --       handlers = {
  --         -- default handler for all servers
  --         function(server_name)
  --           require("lspconfig")[server_name].setup({})
  --         end,
  --         -- you can override per-server like this:
  --         -- ["lua_ls"] = function()
  --         --   require("lspconfig").lua_ls.setup({
  --         --     settings = { ... },
  --         --   })
  --         -- end,
  --       },
  --     },
  --     config = function(_, opts)
  --       -- this will merge your opts and call setup under the hood
  --       require("mason-lspconfig").setup(opts)
  --     end,
  --   },
  --
  --   {
  --     "WhoIsSethDaniel/mason-tool-installer.nvim",
  --     dependencies = { "williamboman/mason.nvim" },
  --     lazy = false,
  --     priority = 1000,
  --     opts = {
  --       ensure_installed = {
  --         "stylua",
  --         "black",
  --         "isort",
  --         "clang-format",
  --       },
  --       run_on_start = true,
  --     },
  --   },
}
